name: Jira PROD Deploy

on:
  repository_dispatch:
    types: [jira-prod-deploy]
  workflow_dispatch:
    inputs:
      jira_issue_key:
        required: true
        type: string
      release_version:
        required: true
        type: string
      deployment_type:
        required: true
        type: choice
        options: [iis, kubernetes]

permissions:
  contents: read
  id-token: write

jobs:
  prod:
    uses: yazicigurkan/bank-devsecops-pipeline-platform/.github/workflows/dotnet-jira-prod-release.yaml@v1.0.0
    with:
      jira_issue_key: ${{ github.event.inputs.jira_issue_key || github.event.client_payload.jira_issue_key }}
      application_name: CHANGE_ME
      repository_name: ${{ github.repository }}
      branch_name: PROD
      release_version: ${{ github.event.inputs.release_version || github.event.client_payload.release_version }}
      deployment_type: ${{ github.event.inputs.deployment_type || github.event.client_payload.deployment_type }}
      target_environment: PROD
      nexus_repository: dotnet-releases
      health_check_url: https://CHANGE_ME.bank.local/health
      rollback_enabled: true
    secrets: inherit
